swap to 12600K + RX6700 for work machine

diff --git a/config/i3/scripts/autoxrandr b/config/i3/scripts/autoxrandr
--- a/config/i3/scripts/autoxrandr
+++ b/config/i3/scripts/autoxrandr
@@ -189,11 +189,13 @@ case $(hostname) in
           xrandr --addmode $gigabyteMonitor "$forcedModeName"
         fi
         runXrandr \
-          --output HDMI-A-0 --mode 1920x1080 --rate 75 --scale 1.5 --pos 0x108 --rotate right \
-          --output DisplayPort-0 --mode 2560x1440 --rate 120 --scale 1 --pos 1620x0 --rotate normal \
-          --output $gigabyteMonitor --mode $forcedModeName --scale 1 --primary --pos 1620x1440 --rotate normal
+          --output HDMI-A-0 --mode 1920x1080 --rate 75 --scale 1.8 --pos 0x108 --rotate right \
+          --output DisplayPort-0 --mode 2560x1440 --rate 120 --scale 1.25 --pos 1944x0 --rotate normal \
+          --output $gigabyteMonitor --mode $forcedModeName --scale 1 --primary --pos 1944x1800 --rotate normal
       exit
     fi
+    echo "[ERROR] no handler for display configuration"
+    exit 1
     ;;
   * )
     echo '[ERROR] unhandled hostname'
